# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Docs

on:
  push:
    branches: [ master ]

    # There is no immediate way to deploy multiple versions to GH Pages but
    # it should be simple to deploy PR and tags to a directory structure such
    # as versions/<tag>/ by changing the FOLDER parameter in the Deploy.
    # We'll need to add that folder to CLEAN_EXCLUDE. To remove versions it
    # would need to be done manually.

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Cache Setup
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install package
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Install Sphinx
      run: |
        pip install sphinx

    - name: Build documentation
      run: |
        cd docs/sphinx
        make html

    - name: Deploy 🚀
      uses: JamesIves/github-pages-deploy-action@3.5.9
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: docs/sphinx/_build/html # The folder the action should deploy.
        CLEAN: true
